import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'
import { fetchContent } from '../utils/contentful'

const Wrapper = styled.div`
  background: hotpink;
`;

export default function Home({cmsData}) {



  const posts = cmsData.fields.imageList;

  return (
    <Wrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>hi</h1>
      {posts.map(post => {
        const imagePath = post.fields.media.fields.file.url;
        console.log(post)
        return (
        <div key={post.fields.slug} className="post">
          {post.fields.title}
          <Image src={`https:${imagePath}`} alt="Picture of the author" width={post.fields.media.fields.file.details.image.width} height={post.fields.media.fields.file.details.image.height}/>
          </div>
        )
      })}
    </Wrapper>
  )
}


export async function getStaticProps() {
  const res = await fetchContent();
  return {
    props: {
      cmsData: res,
    },
  }
}