import Head from 'next/head'
import Image from 'next/image'
import { fetchContent } from '../utils/contentful'

export default function Home({cmsData}) {

  console.log(cmsData)

  const posts = cmsData.fields.imageList;
  console.log(posts)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>hi</h1>
      {posts.map(post => {
        console.log(post)
        const imagePath = post.fields.media.fields.file.url;
        console.log(imagePath)
        return (
        <div key={post.metadata.slug} className="post">
          {post.fields.title}
          <Image src={`https:${imagePath}`} alt="Picture of the author" width={post.fields.media.fields.file.details.image.width} height={post.fields.media.fields.file.details.image.height}/>
          </div>
        )
      })}
    </div>
  )
}


export async function getStaticProps() {
  const res = await fetchContent();
  return {
    props: {
      cmsData: res,
    },
  }
}